services:
  joshsw_dev:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: joshsw_dev
    ports:
      - "8062:8062"
    restart: unless-stopped
    environment:
      - SITE_ENV=PRODUCTION
