services:
  joshsw_dev:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: joshsw_dev
    networks:
      - "public"
    restart: unless-stopped
    environment:
      - SITE_ENV=PRODUCTION
