svg_list: list = [
    "BeekeeperLogo.svg",
    "bootstrap.svg",
    "docker.svg",
    "fa-python.svg",
    "fa-react.svg",
    "fa-sass.svg",
    "fastapi-svg.svg",
    "io-js.svg",
    "postgres.svg",
    "postman.svg",
    "pyscript-sticker-black.svg",
    "si-pwsh.svg",
    "ui-kit.svg",
]
