packages = ["orjson"]
version = "0.1.3"
#interpreter = "/packages/pyodide/0.26.0/full/pyodide/pyodide.mjs"
interpreter = "https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.mjs"

[splashscreen]
autoclose = true

[[fetch]]
from = "https://dev.local:8062/"
# from = "https://phel.ngrok.dev/"
files = [
#    "senza/websocket.py",
    "senza/dom_router.py",
    "senza/components/abase.py",
    "senza/components/div.py",
    "senza/components/__init__.py",
    "web/app.py",
    "web/queries.py",
    "web/context.py",
    "web/vars/svg_list.py",
    "web/views/about_page.py",
    "web/views/dp_life_page.py",
    "web/views/project_page.py",
]
